### ISSUE TITLE
Strip a package from an SBML file

### ISSUE THREAD

**Issue by draeger** [sbmlteam/jsbml#136]
JSBML should be able to remove a package entirely from a model when provided with a namespace or a short label of that package.

**Comment by niko-rodrigue** [comment]
That would be a good function to add. But if you are trying to cover the need of Chris, what they are after is a method that will go through the SBMLDocument and check that all the enabled packages are still needed and disable them if not so that the namespace declaration is not present in the XML if the package is not present any more in the model.

**Comment by cjmyers** [comment]
Correct.  I've added a new issue to explain this better.

**Comment by mephenor** [comment]
Added a PackageDisabler class with a removePackage method to core/src/util that should handle this.
A disableUnused method is also present, which should take care of Issue #137
