### ISSUE TITLE
log4j.properties

### ISSUE THREAD

**Issue by piotr-gawron** [sbmlteam/jsbml#144]
I have issues with the library due to log4j.properties that you included in your release jar file. 

The problem is that when you include your library this log4j config file can be picked as default and override my application log4j properties. I include jsbml using maven, therefore it's very tricky to remove it from jar.

Apart from than, it's considered a good practice to move logger configuration outside of jar because it gives much more flexibility in configuration.

**Comment by niko-rodrigue** [comment]
Hi Piotr, it should not be a problem for you, if you include your own configuration file you can specify it on the command line if needed or if it is on you filesystem at the top level of your project, it should be picked first.
The main problem might that because you include jsbml, you are now using log4j2 and then the properties file is not used any more. You have to define your own configuration in log4j2.xml, then your configuration should be picked first, hopefully.
We want our users to have a default configuration, so we want to keep the configuration file in our jar for now (although in future release we will remove the log4j.properties as it is not used any more).
