### ISSUE TITLE
hardcoded version of internal dependency

### ISSUE THREAD

**Issue by piotr-gawron** [sbmlteam/jsbml#156]
I found a conflicting library versions in the jsbml-1.4 jar provided by maven.

The problem is that there is hardcoded dependency to 1.3.1 version of jsbml-distrib library which depends on the jsbm-core 1.3.1 version, but your main code depends on jsbml-core 1.4. Here is the line responsible for that:
https://github.com/sbmlteam/jsbml/blob/jsbml-1.4/dev/maven/pom.xml#L102

Because of that my integration tests fail -  unresolved conflicts in maven dependency tree can result in very unstable system.

**Comment by niko-rodrigue** [comment]
Thanks for the report. I will try to remove jsbml-core-1.3.1 from the dependency tree and then see if it resolve the problem and no more conflict are shown. If that does not work, I will have to create a jsbml-distrib-1.4 to make things right.

**Comment by niko-rodrigue** [comment]
Could you check the maven artefact JSBML-1.5-SNAPSHOT to see if everything is back to normal for the maven dependencies.

**Comment by piotr-gawron** [comment]
Can you tell me where have you deployed it?

I checked maven central: https://mvnrepository.com/artifact/org.sbml.jsbml/jsbml 
and jitpack https://jitpack.io/#sbmlteam/jsbml
but couldn't find it...

**Comment by niko-rodrigue** [comment]
it is on the snapshot repository of maven central, you should get it without modifying anything in your pom, if snapshots are enabled (I think).
Otherwise, you can add this repo:

<repository>                                                                                                                                  <id>Sonatype-SNAPSHOT</id>                                                                                                                     <name>Sonatype Snapshot repository</name>                                                                                                  <url>https://oss.sonatype.org/content/repositories/snapshots/</url>                                                                       </repository>

**Comment by piotr-gawron** [comment]
I can confirm that the issue is fixed.

Thanks
