### ISSUE TITLE
Issue when parsing math formula

### ISSUE THREAD

**Issue by Fontanapink** [sbmlteam/jsbml#244]
Hi, I am trying to parse a math formula that should look like this:

`((K)^(n))/((K)^(n) + (Y_PhlF)^(n))`

However, when I use the ASTNode parser I get the following result:

`K^n/(K^n+Y_PhlF^n)`

No matter how many parenthesis or in which order I put them, it always returns this formula which has the denominator only diving the "n" and not the "k^n"

**Comment by matthiaskoenig** [comment]
Did you try to use `power(K, n)` instead of `K^n`? At least for libsbml this is the way to write exponents in math formulas. Could be that the same works in JSBML as a work around.

**Comment by Fontanapink** [comment]
`(power(K, n))/(power(K, n) + power(Y_PhlF, n))`

still outputs 

`K^n/(K^n+Y_PhlF^n)`

**Comment by luciansmith** [comment]
Both of your two formulas produce the same ASTNodes, and the same MathML (at least when using libsbml):

```
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <divide/>
            <apply>
              <power/>
              <ci> K </ci>
              <ci> n </ci>
            </apply>
            <apply>
              <plus/>
              <apply>
                <power/>
                <ci> K </ci>
                <ci> n </ci>
              </apply>
              <apply>
                <power/>
                <ci> Y_PhlF </ci>
                <ci> n </ci>
              </apply>
            </apply>
          </apply>
        </math>
```

The ASTNode-to-infix translator assumes that "^" has precedence over "/", so it doesn't insert extra parentheses.  If you're working with something that parses infix directly, and it's interpreting the "/" as having precedence over the "^", the only easy solution I can see is to add a new variable and call it something like "K_to_the_n" and give it an assignment rule to equal K^n.  

If instead the problem is just visual, you could perhaps say in the documentation that "^" takes precedence over everything else?

If the problem is that those two strings produce *different* MathML in jsbml, that's a jbsbml bug!

**Comment by Fontanapink** [comment]
I tried doing:
`numerator = "((" + K + ")^(" + n + "))";
denominator = "((" + K + ")^(" + n + ") + (" + input_flux +")^(" + n + "))";
kineticLaw = "(" + numerator + ")/(" + denominator + ")";`

Still doesn't work. I'll check your other proposed solutions

**Comment by luciansmith** [comment]
What is it that 'doesn't work'?  It won't ever put parentheses into produced infix that it doesn't think it needs, but the underlying math should be the same.  Are you asking for a mode of infix production that inserts extra parentheses everywhere, just for visual purposes?

**Comment by Fontanapink** [comment]
I am sorry maybe I am not being clear. I want the output to look like this:
![image](https://user-images.githubusercontent.com/12236668/156236182-484d424f-b8aa-42a8-b618-0fd616449b8a.png)

But instead it returns this:

![image](https://user-images.githubusercontent.com/12236668/156236262-9aa1075b-db0a-421c-b53e-6c1f7065069e.png)

**Comment by luciansmith** [comment]
What is the MathML that you are getting?  Or, alternatively, what is the root ASTNode function?  All of your infix lines, with and without parentheses, in libsbml, produce the same MathML.  The same *should* be true of jsbml, and if not, it's a bug.  The root ASTNode should be a 'divide' function, with the first argument a 'power' function with children 'K' and 'n'.  The second argument of the divide function will be a 'plus', and the children of the 'plus' are both 'power' functions, the first with children 'K' and 'n', and the second with children 'Y_PhIF' and 'n'.

In other words:

```
K^n/(K^n+Y_PhlF^n)"
```
produces:

```
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <divide/>
            <apply>
              <power/>
              <ci> K </ci>
              <ci> n </ci>
            </apply>
            <apply>
              <plus/>
              <apply>
                <power/>
                <ci> K </ci>
                <ci> n </ci>
              </apply>
              <apply>
                <power/>
                <ci> Y_PhlF </ci>
                <ci> n </ci>
              </apply>
            </apply>
          </apply>
        </math>
```
just like you want.

In sbml-produced infix, "^" takes precedence over "/" and "*" and "+" and "-".  You've assumed the latter, since you haven't complained that "K^n+Y_PhlF^n" means "K^(n+Y_PhIF)^n" or something.  But it applies to the former as well:  first the "^" functions are grouped, and then the "*" and "/" are grouped, and finally the "+" and "-". 

This is not necessarily a universal convention for infix, but it's the one that libsbml and jsbml have assumed.

However, I can't imagine how 
```
numerator = K^n
denominator=K^n+Y_PhIF^n
kl = numerator/denominator
```
could possibly 'not work'.  What is the context in which they do not work?

**Comment by matthiaskoenig** [comment]
I don't understand what your problem is. 
From the description it could be the tool that you use to look at the MathML is faulty. The problem is that many Content MathML to Presentation MathML conversions are flawed, especially if they are based on XSLT conversions. I.e. everything is correct in SBML, but the tool you use to render the MathML does not work correctly ;)

Did you try to look with https://sbml4humans.de at your SBML model. We put a lot of effort into making and rendering the Content MathML correctly.

**Comment by Fontanapink** [comment]
Thanks that helped! It was just the string that was being displayed incorrectly, the mathML actually is correct. Thanks!
